### ISSUE TITLE
Translation don't work because of the *.po files 

### ISSUE THREAD

**Issue by StefWe** [ubports/ubuntu-ui-extras#3]
There is a small issue in some of the *.po files.
![wrongpofilestructer](https://user-images.githubusercontent.com/35935077/39544475-7b70ead4-4e4e-11e8-8a10-10b8c0ef82f2.png)

So the translation is not working correct. We need to check when we generate the .po files from weblate that everything is correct.

**Comment by StefWe** [comment]
@Flohack74 any chance to fix this the same way you did it on the gallery-app?

**Comment by Flohack74** [comment]
Weblate will only regenerate the po files if there is an update to the pot file. So it sufficient to touch the pot file and add a blank line maybe ;) or you fix smth there.

**Comment by StefWe** [comment]
@Flohack74 we changed the pot file 8 days ago or simething #2

**Comment by StefWe** [comment]
@ Flohack74 we changed the pot file 8 days ago.

**Comment by Flohack74** [comment]
There are more issues, can you fix this duplication please:

 ```
#: modules/Ubuntu/Components/Extras/PhotoEditor/EditStack.qml:128
 #: modules/Ubuntu/Components/Extras/PhotoEditor/EditStack.qml:128
-msgid "Revert to Original"
-msgstr "Original wiederherstellen"
-
 #: modules/Ubuntu/Components/Extras/PhotoEditor.qml:196
 #: modules/Ubuntu/Components/Extras/PhotoEditor.qml:196
 msgid "Revert to original"
 msgid "Revert to original"
 msgstr "Original wiederherstellen"
```

**Comment by Flohack74** [comment]
So that Original is original, and the msgid is not duplicted?

**Comment by Flohack74** [comment]
Disregard, seems its fixed now...

**Comment by StefWe** [comment]
The msgid with the original looks good now.

But the string you can see at the top of this topic is not correct with this double " " bevor the translation.
Is there something i need to change in the pot file?

**Comment by Flohack74** [comment]
Yes you just need to delete this "" probably and remove the line break.

**Comment by StefWe** [comment]
You mean in the de.po file? But this file comes from weblate, isn't it?
I don't see the diffrent in the pot file, to the other tags why this happend at this msgid and the others are ok

**Comment by Flohack74** [comment]
Hmm strange now I understand. Basically po files should be regenerated. I dont see why this persists. Eventually we have to fix all of them manually, but boring...

**Comment by StefWe** [comment]
If fix them manually and make a PR

**Comment by StefWe** [comment]
The changes from #8 don't take effect on my xenial test device.

When i look on CI system i can see the #13 is the last succeded build. In which system update is this version deliverd?

**Comment by Flohack74** [comment]
Hmm I will check mabye its not integrated into the image at all...

**Comment by Flohack74** [comment]
I checked, and all is there. Can you please check the version no of the deb package on your system: 
should be qtdeclarative5-ubuntu-ui-extras0.2_0.4+ubports+0~20180513063203.13~1.gbpa72035

**Comment by StefWe** [comment]
![photo_2018-05-17_22-20-20](https://user-images.githubusercontent.com/35935077/40201859-9f6c720e-5a20-11e8-9cac-d74b15ecf439.jpg)

sorry for the bad quality of the picture. It looks like the version is the right one.

**Comment by Flohack74** [comment]
Yes so basically you should have the latest version. Did anything change in yesterdays or todays upate?

**Comment by StefWe** [comment]
No, nothing changed since the last couple of updates.

Is there a option to get the .deb files from jenkins and take a look "inside" if the changes really there?

**Comment by StefWe** [comment]
maybe it is a problem that there are two versions installed? i can see version 0.1 and version 0.2 on the picture above.

**Comment by StefWe** [comment]
i found the bug report for the same problem on launchpad
https://bugs.launchpad.net/canonical-devices-system-image/+bug/1521222
