### ISSUE TITLE
Cropping an image increases the file size (compression ratio)

### ISSUE THREAD

**Issue by myii** [ubports/ubuntu-ui-extras#30]
Transferring over from https://gitlab.com/ubports/apps/gallery-app/issues/95.

CC: @StefWe.

**Comment by StefWe** [comment]
I have searched in ubuntu-ui-extras and found that the quality is set to 90. So it should compress the picture.

https://doc-snapshots.qt.io/qt5-5.9/qimage.html#save

https://github.com/ubports/ubuntu-ui-extras/blob/925cb3ebb67a0baab28bea390b544af48970de2b/modules/Ubuntu/Components/Extras/plugin/photoeditor/photo-edit-thread.cpp#L107-L108

I don't see the why it is not working.

**Comment by StefWe** [comment]
With -1 as quality parameter it use the same compression as the picture has before.

![Screenshot_20190415_130608](https://user-images.githubusercontent.com/35935077/56128458-f9539300-5f7f-11e9-8fd8-6375b34002aa.png)

Can we live with that?

**Comment by myii** [comment]
@StefWe As mentioned in our discussion in the [Telegram](https://t.me/UbuntuAppDevEN) group, using `-1` sounds like the right solution in the circumstances.

**Comment by UniversalSuperBox** [comment]
Fixed by #31
